### ISSUE TITLE
Fatal Error when executing hook

### ISSUE THREAD

**Issue by zf2timo** [captainhookphp/captainhook#175]
Recently I replaced captainhook 3.1 via composer with captainhook 5.10 via phive. The first days everything worked as usual. But now there is always an exception when a hook is executed:
```bash
/home/zf2timo/.phive/phars/captainhook-5.10.7.phar  hook:pre-commit --no-interaction --configuration=captainhook.json --bootstrap=vendor/autoload.php
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function CaptainHook\App\Runner\Hook::__construct(), 3 passed in phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/src/Console/Command/Hook.php on line 70 and exactly 4 expected in /home/zf2timo/git/apis/project/vendor/captainhook/captainhook/src/Runner/Hook.php:51
Stack trace:
#0 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/src/Console/Command/Hook.php(70): CaptainHook\App\Runner\Hook->__construct()
#1 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/vendor/symfony/console/Command/Command.php(228): CaptainHook\App\Console\Command\Hook->execute()
#2 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/vendor/symfony/console/Application.php(854): CaptainHook\Ext\Symfony\Component\Console\Command\Command->run()
#3 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/vendor/symfony/console/Application.php(224): CaptainHook\Ext\Symfony\Component\Console\Application->doRunCommand()
#4 phar:///home/zf2timo/.phive/phars/captainhook-5.10 in /home/zf2timo/git/apis/project/vendor/captainhook/captainhook/src/Runner/Hook.php on line 51

Fatal error: Uncaught ArgumentCountError: Too few arguments to function CaptainHook\App\Runner\Hook::__construct(), 3 passed in phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/src/Console/Command/Hook.php on line 70 and exactly 4 expected in /home/zf2timo/git/apis/project/vendor/captainhook/captainhook/src/Runner/Hook.php on line 51

ArgumentCountError: Too few arguments to function CaptainHook\App\Runner\Hook::__construct(), 3 passed in phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/src/Console/Command/Hook.php on line 70 and exactly 4 expected in /home/zf2timo/git/apis/project/vendor/captainhook/captainhook/src/Runner/Hook.php on line 51
```
I already reinstalled captianhook and created a new configuration file and created new hooks:
```json
{
	"commit-msg": {
		"enabled": true,
		"actions": []
	},
	"pre-push": {
		"enabled": false,
		"actions": []
	},
	"pre-commit": {
		"enabled": true,
		"actions": [
			{
				"action": "vendor/bin/phplint",
				"options": [],
				"conditions": []
			},
			{
				"action": "bin/phpunit -c ./phpunit.xml --no-coverage",
				"options": [],
				"conditions": []
			},
			{
				"action": "vendor/bin/phpcs --runtime-set ignore_errors_on_exit 0 --filter=GitStaged",
				"options": [],
				"conditions": []
			}
		]
	},
	"prepare-commit-msg": {
		"enabled": false,
		"actions": []
	}
}
```

```bash
#!/bin/sh

# installed by CaptainHook 5.10.7

INTERACTIVE="--no-interaction"

/home/zf2timo/.phive/phars/captainhook-5.10.7.phar $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:pre-commit "$@" <&0
```

This is my phars.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">
  <phar name="composer-normalize" version="^2.15.0" installed="2.23.1" location="./bin/composer-normalize" copy="false"/>
  <phar name="phpunit" version="^9.5.14" installed="9.5.14" location="./bin/phpunit" copy="false"/>
  <phar name="phpstan" version="^1.0" installed="1.4.6" location="./bin/phpstan" copy="false"/>
  <phar name="captainhook" version="^5.10.7" installed="5.10.7" location="./bin/captainhook" copy="false"/>
</phive>
```

The Error is independent from the PHP version. I tried it in PHP 7.4, PHP 8.0 and PHP 8.1.

Any Idea whats wrong here?

**Comment by sebastianfeldmann** [comment]
Good question. I just created a project with your exact settings and it worked just fine. I also tried multiple PHP versions and saw no differences.

The `Runner` expects 3 arguments not 4 as mentioned in the error message you posted.

```php
public function __construct(IO $io, Config $config, Repository $repository)
```

Are you sure you removed all `CaptainHook` classes located in `vendor/*` because the version `3.1.0` you had installed earlier uses 4 arguments.

```php 
public function __construct(IO $io, Config $config, Repository $repository, Options $arguments)
```

**Comment by zf2timo** [comment]
Wow, thanks! That is the problem.  But I have no idea, why it still uses something from the `vendor` folder. I use the absolute Path to execute the phar file:

```bash
➜  project git:(feature/auto-headline-level) ✗ /home/zf2timo/.phive/phars/captainhook-5.10.7.phar $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:pre-commit "$@"
pre-commit: 
 - vendor/bin/phplint                                                : done
 - bin/phpunit -c ./phpunit.xml --no-coverage                        : done
 - vendor/bin/phpcs --runtime-set ignore_errors_on_exit 0 --filte... : done
➜  project git:(feature/auto-headline-level) ✗ mv vendor/captainhook{-bu,}
➜  project git:(feature/auto-headline-level) ✗ /home/zf2timo/.phive/phars/captainhook-5.10.7.phar $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:pre-commit "$@"
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function CaptainHook\App\Runner\Hook::__construct(), 3 passed in phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/src/Console/Command/Hook.php on line 70 and exactly 4 expected in /home/zf2timo/git/apis/project/vendor/captainhook/captainhook/src/Runner/Hook.php:51
Stack trace:
#0 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/src/Console/Command/Hook.php(70): CaptainHook\App\Runner\Hook->__construct()
#1 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/vendor/symfony/console/Command/Command.php(228): CaptainHook\App\Console\Command\Hook->execute()
#2 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/vendor/symfony/console/Application.php(854): CaptainHook\Ext\Symfony\Component\Console\Command\Command->run()
#3 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/vendor/symfony/console/Application.php(224): CaptainHook\Ext\Symfony\Component\Console\Application->doRunCommand()
#4 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/vendor/symfony/console/Application.php(136): CaptainHook\Ext\Symfony\Component\Console\Application->doRun()
#5 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/bin/captainhook(63): CaptainHook\Ext\Symfony\Component\Console\Application->run()
#6 phar:///home/zf2timo/.phive/phars/captainhook-5.10.7.phar/bin/captainhook(64): CaptainHook\Ext\{closure}()
#7 /home/zf2timo/.phive/phars/captainhook-5.10.7.phar(17): require('...')
#8 {main}
  thrown in /home/zf2timo/git/apis/project/vendor/captainhook/captainhook/src/Runner/Hook.php on line 51
```

Maybe the composer autoloader from the project is registered and loads classes from the `vendor`? :thinking:

**Comment by sebastianfeldmann** [comment]
I think it's some autoloader magic happening from the PHAR compilation done by `Box` and the `vendor/autoload.php` file and somehow the `vendor` stuff takes precedence.

**Comment by zf2timo** [comment]
Thank you, for the help.
