### ISSUE TITLE
PHP Fatal error:  Argument #2 ($filter) must be of type array

### ISSUE THREAD

**Issue by michielgerritsen** [captainhookphp/captainhook#228]
Hello,

When running a `git commit`, I'm bumping into this error on the latest version:
```
PHP Fatal error:  Uncaught TypeError: CaptainHook\App\Hook\Condition\FileStaged\OfType::__construct(): Argument #2 ($filter) must be of type array, string given, called in /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Runner/Condition.php on line 118 and defined in /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Hook/Condition/FileStaged/OfType.php:65
Stack trace:
#0 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Runner/Condition.php(118): CaptainHook\App\Hook\Condition\FileStaged\OfType->__construct('php', 'phtml')
#1 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Runner/Condition.php(81): CaptainHook\App\Runner\Condition->createCondition(Object(CaptainHook\App\Config\Condition))
#2 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Runner/Hook.php(396): CaptainHook\App\Runner\Condition->doesConditionApply(Object(CaptainHook\App\Config\Condition))
#3 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Runner/Hook.php(316): CaptainHook\App\Runner\Hook->doConditionsApply(Array)
#4 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Runner/Hook.php(264): CaptainHook\App\Runner\Hook->handleAction(Object(CaptainHook\App\Config\Action))
#5 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Runner/Hook.php(244): CaptainHook\App\Runner\Hook->executeFailOnFirstError(Array)
#6 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Runner/Hook.php(166): CaptainHook\App\Runner\Hook->executeActions(Array)
#7 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Runner/Hook.php(148): CaptainHook\App\Runner\Hook->runHook(Array)
#8 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Console/Command/Hook.php(92): CaptainHook\App\Runner\Hook->run()
#9 /Users/michielgerritsen/Sites/my-project/vendor/symfony/console/Command/Command.php(326): CaptainHook\App\Console\Command\Hook->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/michielgerritsen/Sites/my-project/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/michielgerritsen/Sites/my-project/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(CaptainHook\App\Console\Command\Hook\PreCommit), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/michielgerritsen/Sites/my-project/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/bin/captainhook(80): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#14 /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/bin/captainhook(82): {closure}(Array)
#15 /Users/michielgerritsen/Sites/my-project/vendor/bin/captainhook(120): include('/Users/michielg...')
#16 {main}
  thrown in /Users/michielgerritsen/Sites/my-project/vendor/captainhook/captainhook/src/Hook/Condition/FileStaged/OfType.php on line 65
```

This error occurred after updating from 5.16.4 to 5.17.1. I've tried it on 5.17.2, but I'm still getting the same error. When rolling back to 5.16.4 the error is gone. I'm running on PHP 8.1.

**Comment by sebastianfeldmann** [comment]
Can you show me configuration of your `FileStaged` condition?

I think there shouldn't be any second argument, at least not in version 5.16.*

```
            {
                "action": "tools/composer verify",
                "conditions": [
                    {
                        "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\Any",
                        "args": [
                            ["composer.json", "composer.lock"]
                        ]
                    }
                ]
            }
```

Since version 5.17.* there is a second argument

```
            {
                "action": "tools/composer verify",
                "conditions": [
                    {
                        "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\Any",
                        "args": [
                            ["composer.json", "composer.lock"],
                            ["C"]
                        ]
                    }
                ]
            }
```

**Comment by sebastianfeldmann** [comment]
Ah I see your issue:

You configured it like this

```
            {
                "action": "your-action",
                "conditions": [
                    {
                        "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
                        "args": [
                            "php",
                            "phtml"
                        ]
                    }
                ]
            }
```

Sadly the `OffType` condition only accepts one "type", if you want to check `php` and `phtml` files you have to configure it like this. I will try to implement it in a way it accepts multiple types. But it will take a while.

```
            {
                "action": "your-action",
                "conditions": [
                    {
                        "exec": "\\CaptainHook\\App\\Hook\\Condition\\Logic\\LogicOr",
                        "args": [{
                            "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
                            "args": [
                              "php"
                            ]
                          },{
                            "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
                            "args": [
                              "phtml"
                            ]
                          }]
                    }
                ]
            }
```

**Comment by michielgerritsen** [comment]
Hi @sebastianfeldmann,

Thanks for looking into this, and you are right: I was trying to run Code Sniffer for both php and phtml files. Unfortunately, your solution didn't work (`Uncaught Error: Call to private CaptainHook\App\Hook\Condition\Logic::__construct()`), but I solved this by removing the phtml extension, as it doesn't make sense in the current project.

**Comment by sebastianfeldmann** [comment]
I'm workin on a solution so you can use `["php", "phtml"]` instead of this logic monster.

Should be released later today.

**Comment by sebastianfeldmann** [comment]
Ass referenced in cac493cfacf14f3a2d16b4ebff9a3bc9adb4c68d 

With CaptainHook 5.17.3 you can now use on of the following

```
            {
                "action": "your-action",
                "conditions": [
                    {
                        "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
                        "args": [
                            ["php", "phtml"]
                        ]
                    }
                ]
            }
```

```
            {
                "action": "your-action",
                "conditions": [
                    {
                        "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
                        "args": [
                            "php,phtml"
                        ]
                    }
                ]
            }
```

Thanks for reporting the issue. It lead down a rabbit whole of things I forgot to change properly for the new `ConfigDependant` conditions.

I will close this issue, but if you have any further problem with this feel free to reopen it at any time.
