### ISSUE TITLE
Issue with 5.1.2 version

### ISSUE THREAD

**Issue by antoinekociuba** [CaptainHookPhp/captainhook#80]
Hi,

I get the following error on 5.1.2 version, which is not present on 5.1.1:

```
~/www/xxx/htdocs> git commit --cleanup=whitespace --allow-empty --file=/var/folders/9j/cdpx8gks7r18f1pscsnybcsm0000gn/T/smartgit-17824646918419494257tmp/commit-3531327082774907137.tmp
[32mNo syntax errors detected[39m
Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() in /Users/antoine/www/xxx/htdocs/vendor/sebastianfeldmann/cli/src/Processor/Symfony.php:36
Stack trace:
#0 /Users/antoine/www/~/www/xxx/htdocs> git commit --cleanup=whitespace --allow-empty --file=/var/folders/9j/cdpx8gks7r18f1pscsnybcsm0000gn/T/smartgit-17824646918419494257tmp/commit-3531327082774907137.tmp
[32mNo syntax errors detected[39m
Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() in /Users/antoine/www/xxx/htdocs/vendor/sebastianfeldmann/cli/src/Processor/Symfony.php:36
Stack trace:
#0 /Users/antoine/www/xxx/htdocs/vendor/captainhook/captainhook/src/Runner/Action/Cli.php(51): SebastianFeldmann\Cli\Processor\Symfony->run('vendor/bin/phpc...')
#1 /Users/antoine/www/xxx/htdocs/vendor/captainhook/captainhook/src/Runner/Hook.php(160): CaptainHook\App\Runner\Action\Cli->execute(Object(CaptainHook\App\Console\IO\DefaultIO), Object(SebastianFeldmann\Git\Repository), Object(CaptainHook\App\Config\Action))
#2 /Users/antoine/www/xxx/htdocs/vendor/captainhook/captainhook/src/Runner/Hook.php(129): CaptainHook\App\Runner\Hook->executeCliAction(Object(CaptainHook\App\Config\Action))
#3 /Users/antoine/www/xxx/htdocs/vendor/captainhook/captainhook/src/Runner/Hook.php(103): CaptainHook\App\Runner\Hook->handleAction(Ob in /Users/antoine/www/xxx/htdocs/vendor/sebastianfeldmann/cli/src/Processor/Symfony.php on line 36
/htdocs/vendor/captainhook/captainhook/src/Runner/Action/Cli.php(51): SebastianFeldmann\Cli\Processor\Symfony->run('vendor/bin/phpc...')
#1 /Users/antoine/www/xxx/htdocs/vendor/captainhook/captainhook/src/Runner/Hook.php(160): CaptainHook\App\Runner\Action\Cli->execute(Object(CaptainHook\App\Console\IO\DefaultIO), Object(SebastianFeldmann\Git\Repository), Object(CaptainHook\App\Config\Action))
#2 /Users/antoine/www/xxx/htdocs/vendor/captainhook/captainhook/src/Runner/Hook.php(129): CaptainHook\App\Runner\Hook->executeCliAction(Object(CaptainHook\App\Config\Action))
#3 /Users/antoine/www/xxx/htdocs/vendor/captainhook/captainhook/src/Runner/Hook.php(103): CaptainHook\App\Runner\Hook->handleAction(Ob in /Users/antoine/www/xxx/htdocs/vendor/sebastianfeldmann/cli/src/Processor/Symfony.php on line 36
```

Maybe the best way to support of more range of Symfony version would be to do something like the following: 

```
if (method_exists('Symfony\Component\Process\Process', 'fromShellCommandline')) {
        $process = Process::fromShellCommandline($command);
} else {
        $process = new Process($command);
}
```

Thank you in advance for your help

**Comment by sebastianfeldmann** [comment]
I added the he condition to the the latest `cli` version 3.2.5.
If you run `composer update` it should work again.
Please give it a try

**Comment by sebastianfeldmann** [comment]
Thanks for reporting the issue ;)

**Comment by antoinekociuba** [comment]
Hi @sebastianfeldmann,

Thank you a lot for your quick fix, working perfectly! ;)
